"""
Euclid DR1 footprint overlay helpers. Visualisation only - Euclid is not an LTS input.
The footprint JSON is generated by make_euclid_footprint.py.
"""
import json
import os

import numpy as np
import plotly.graph_objects as go
import streamlit as st

EUCLID_FOOTPRINT_PATH = os.path.join('.', 'euclidFields', 'euclid_dr1_footprint.json')


@st.cache_data
def load_euclid_footprint(path=EUCLID_FOOTPRINT_PATH):
    """Loads the pre-computed Euclid DR1 footprint polygons, or None if missing."""
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def get_euclid_if_enabled():
    """Returns the footprint if the sidebar toggle is on, warning if the file is missing."""
    if not st.session_state.get("euclid_toggle", False):
        return None
    data = load_euclid_footprint()
    if data is None:
        st.warning(f"Euclid footprint not found at {EUCLID_FOOTPRINT_PATH}. "
                   "Generate it with `python make_euclid_footprint.py`.")
    return data


def add_euclid_to_fig(fig, data):
    """Draws the Euclid DR1 footprint as dashed outlines only."""
    for n, area in enumerate(data.get("year1Areas", [])):
        RA = area.get('RA', [])
        Dec = area.get('Dec', [])
        if not RA or not Dec:
            continue

        coords = np.array([[r, d] for r, d in zip(RA, Dec)])
        if not np.array_equal(coords[0], coords[-1]):
            coords = np.vstack([coords, coords[0]])

        fig.add_trace(go.Scatter(x=coords[:, 0], y=coords[:, 1], mode="lines",
                                 line=dict(color="#00e5ff", width=2, dash="dash"),
                                 legendgroup="euclid", showlegend=(n == 0), name="Euclid DR1",
                                 hovertext=area.get('name', 'Euclid DR1'), hoverinfo="text"))
